# Generated by Django 3.1 on 2020-09-30 20:32

from django.db import migrations

def update_status_new_to_pending(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    qs = UserProfile.objects.filter(status='NEW')
    for user_profile in qs:
        user_profile.status='PENDING'
        user_profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200930_2008'),
    ]

    operations = [
        migrations.RunPython(update_status_new_to_pending),
    ]
