# Generated by Django 3.1 on 2020-10-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200930_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtoken',
            name='token',
            field=models.CharField(default='#deftoken#', max_length=150),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
