# Generated by Django 3.1 on 2021-03-02 07:18

from django.db import migrations


def seed_team_data(apps, schema_editor):
    Team = apps.get_model('api', 'Team')
    Team.objects.bulk_create([
        Team(name="Event Volunteers"),
        Team(name="Hackathon Volunteers"),
        Team(name="Host Management"),
        Team(name="Partnership Management"),
        Team(name="Social Media"),
        Team(name="Tech Event Volunteers"),
        Team(name="Volunteer Management"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210302_0713'),
    ]

    operations = [
        migrations.RunPython(seed_team_data),
    ]
