# Generated by Django 3.1 on 2021-04-06 18:14

from django.db import migrations


def seed_role_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.bulk_create([
        Role(name="VOLUNTEER"),
        Role(name="LEADER"),
        Role(name="DIRECTOR"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210406_1812'),
    ]

    operations = [
        migrations.RunPython(seed_role_data),
    ]
