# Generated by Django 3.1 on 2021-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210406_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('VOLUNTEER', 'VOLUNTEER'), ('LEADER', 'LEADER'), ('DIRECTOR', 'DIRECTOR')], max_length=20, null=True),
        ),
    ]
