# Generated by Django 3.1 on 2021-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210419_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('edit_link', models.CharField(max_length=255)),
                ('published_link', models.CharField(max_length=255)),
            ],
        ),
    ]
