# Generated by Django 3.1 on 2022-03-22 23:45

from django.db import migrations
from ..models import Team


def add_tech_blogger_team(apps, schema_editor):
    new_team_name = "Tech Bloggers"
    db_teams = apps.get_model('api', 'Team')
    teams = db_teams.objects.values_list('name', flat=True)

    if new_team_name not in teams:
        Team(name=new_team_name).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_userprofile_role'),
    ]

    operations = [
        migrations.RunPython(add_tech_blogger_team),
    ]
